"""Initial migration

Revision ID: c5164d9c7ecd
Revises: 
Create Date: 2024-08-15 20:51:35.263768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5164d9c7ecd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        # Adjusting the length of image_file in journal_entry
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        
        # Ensuring is_public remains non-nullable
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        
        # Dropping unwanted columns from journal_entry
        batch_op.drop_column('journey_date')
        batch_op.drop_column('day')
        batch_op.drop_column('journey_title')

    # No need to add image_file to the user table, as it already exists
    # Commenting out the addition of the image_file column to user
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Dropping the image_file column from user if we need to downgrade
        # Note: This will only be needed if image_file was added during the migration, which it's not in this case
        batch_op.drop_column('image_file')

    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        # Revert changes made to journal_entry during the upgrade
        batch_op.add_column(sa.Column('journey_title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('journey_date', sa.DATE(), autoincrement=False, nullable=True))
        
        # Revert is_public back to nullable
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)

        # Revert the length of image_file in journal_entry back to 100 characters
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
