"""Add public/private toggle to journal entries

Revision ID: 760540e2f824
Revises: 508bcec9b3ef
Create Date: 2024-08-13 17:56:27.700153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760540e2f824'
down_revision = '508bcec9b3ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
