"""Recreate migration for JSON content field

Revision ID: ad9dbd112147
Revises: 544595da1910
Create Date: 2024-08-28 19:10:10.887897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9dbd112147'
down_revision = '544595da1910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_section')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    op.create_table('journal_section',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('journal_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], name='journal_section_journal_entry_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='journal_section_pkey')
    )
    # ### end Alembic commands ###
