"""Add JournalSection model

Revision ID: dc79a3a0a8f5
Revises: c5164d9c7ecd
Create Date: 2024-08-17 19:32:55.111341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc79a3a0a8f5'
down_revision = 'c5164d9c7ecd'
branch_labels = None
depends_on = None


def upgrade():
    # Ensure all NULL values in image_file are updated before applying the NOT NULL constraint
    op.execute("UPDATE \"user\" SET image_file = 'default.jpg' WHERE image_file IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_file', sa.String(length=255), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.drop_table('journal_section')
    # ### end Alembic commands ###
